name: modul2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  http: ^1.1.0
  shared_preferences: ^2.0.6
  webview_flutter: ^4.2.2
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  firebase_messaging: ^14.6.6
  flutter_local_notifications: ^15.1.0+1

  image: 4.1.3
  flutter:
    sdk: flutter
  image_picker:

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - lib/images/
  uses-material-design: true
