// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSxVSfJIqkIS_DV6CZEHGBppnCgc-Rwlg',
    appId: '1:347441987380:web:c8a1b84142612ed9062f61',
    messagingSenderId: '347441987380',
    projectId: 'wide-cathode-404703',
    authDomain: 'wide-cathode-404703.firebaseapp.com',
    storageBucket: 'wide-cathode-404703.appspot.com',
    measurementId: 'G-4V5CK2TSYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpTGWDV3Tfp5LQLHSgvWL2c-V6XdQvulA',
    appId: '1:347441987380:android:169869d7b387f0fa062f61',
    messagingSenderId: '347441987380',
    projectId: 'wide-cathode-404703',
    storageBucket: 'wide-cathode-404703.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEohRobVs2whC0CBZTHyDM7whm4AkVAjo',
    appId: '1:347441987380:ios:cdc30402c765a265062f61',
    messagingSenderId: '347441987380',
    projectId: 'wide-cathode-404703',
    storageBucket: 'wide-cathode-404703.appspot.com',
    iosBundleId: 'com.praktikum.modul2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEohRobVs2whC0CBZTHyDM7whm4AkVAjo',
    appId: '1:347441987380:ios:3d8e04e173f4ca8b062f61',
    messagingSenderId: '347441987380',
    projectId: 'wide-cathode-404703',
    storageBucket: 'wide-cathode-404703.appspot.com',
    iosBundleId: 'com.praktikum.modul2.RunnerTests',
  );
}
